remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Eric West
description: I'm a geospatial professional, data analyst, and project manager based in Roanoke, Virginia.<br><br>I encourage you to explore my <a href="https://completingthemap.com/smokies">smokies</a> and <a href="https://completingthemap.com/ciderguide">ciderguide</a> repositories for examples of my work.
