remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Eric West
description: I am a geospatial professional, data analyst, project manager, cider expert, and educator based in Roanoke, Virginia. See my GitHub profile for my current projects.
