remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Eric West
description: I'm a geospatial professional, data analyst, and project manager based in Roanoke, Virginia.<br><br>Explore my <a href="https://github.com/ericallanwest/smokies">smokies</a> and <a href="https://github.com/ericallanwest/ciderguide">ciderguide</a> repos.
